### ISSUE TITLE
Validation on Option<_> should validate the contained type

### ISSUE THREAD

**Issue by not-my-profile** [nsat/validatron#14]
[keats/validator](https://github.com/Keats/validator) does it this way and I think it's very handy. Currently e.g.:

```rust
#[derive(Validate)]
struct Thing {
    #[validatron(max = 5)]
    pub age: Option<i32>
}
```

fails with:

> mismatched types
> expected enum `std::option::Option<i32>`
>    found type `{integer}`

**Comment by spire-ffoston** [comment]
While it's not the cleanest interface, #17 added a way to cover this use case.
