### ISSUE TITLE
Wording of error messages

### ISSUE THREAD

**Issue by not-my-profile** [nsat/validatron#15]
> {} != {}

Non-programmers might not understand this syntax. Wording it `must equal {}` or sth. like that would make the error message more accessible.

> 3 is less than 5

That's not an error, that's a correct statement. I'd prefer wording it like `must be greater or equal than {}`.

**Comment by spire-ffoston** [comment]
Thanks for raising this, you should find a brand new `v0.2.1` release with some revised error messages in.
